<?php

function dna_menu() {
  $items['path-to-ajax/%/%'] = array(
    'access arguments' => array('access content'),
    'page callback' => 'dna_ajax_callback',
    'page arguments' => array(1,2),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function dna_ajax_callback($js, $node_id) {
  $node = node_load($node_id);

  if ($js == 'nojs') {
    drupal_goto('node/' . $node->nid);
  }

  $build = node_view($node);
  $html = render($build);

  $commands = array();
  $commands[] = ajax_command_html('#dna-ajax-wrapper', $html);

  print ajax_render($commands);
  exit;
}
