<?php

function helix_menu() {
    $items['double_helix'] = array(
        'title' => 'Generate DNA Sequence',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('helix_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['generated_helix'] = array(
        'title' => 'Helix Results',
        'page callback' => 'helix_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

// function dna_user_login(&$edit, $account) {
//     $_GET['destination'] = 'home';
// }

function helix_form() {
    $form['dna_sequence'] = array(
        '#title' => 'DNA Helix',
        '#type' => 'textfield',
        '#description' => t('Please enter half of a DNA helix to generate the other half.'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    return $form;
}


function generate_dna($dna_sequence) {
    $dna_input_array = str_split(strtoupper($dna_sequence));
    $converted_dna_array = [];

    for ($i = 0; $i < count($dna_input_array); $i++){
        if($dna_input_array[$i] === 'A') {
            $dna_input_array[$i] = 'T';
            array_push($converted_dna_array, $dna_input_array[$i]);
        }
        else if($dna_input_array[$i] === 'T') {
            $dna_input_array[$i] = 'A';
            array_push($converted_dna_array, $dna_input_array[$i]);
        }
        else if($dna_input_array[$i] === 'C') {
            $dna_input_array[$i] = 'G';
            array_push($converted_dna_array, $dna_input_array[$i]);
        }
        else if($dna_input_array[$i] === 'G') {
            $dna_input_array[$i] = 'C';
            array_push($converted_dna_array, $dna_input_array[$i]);
        }
        else {
            $dna_input_array[$i];
        }
    }
    return join($converted_dna_array);
}

function helix_form_submit($form, &$form_state) {
    $dna_sequence = $form_state['values']['dna_sequence'];
    $result = generate_dna($dna_sequence);
    $_SESSION['opposite_helix'] = $result;

    $form_state['redirect'] = 'generated_helix';
}

function helix_success() {
    $generated_helix = $_SESSION['opposite_helix'];
    echo '<pre>';
    print_r($generated_helix);
    echo '</pre>';
    return '<p>The other side of your helix is: ' . $generated_helix . '</p>';
}
