<?php

function helix_menu() {
    $items['double_helix'] = array(
        'title' => 'Generate DNA Sequence',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('helix_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function helix_form() {
    $form['dna_sequence'] = array(
        '#title' => 'DNA Helix',
        '#type' => 'textfield',
        '#description' => t('Please enter half of a DNA helix to generate the other half.'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    return $form;
}

function generate_dna($input) {
    $dna_input_array = str_split(strtoupper($input));

    for ($i = 0; $i < count($dna_input_array); $i++){
        if($dna_input_array[$i] === 'A') {
            $dna_input_array[$i] = 'T';
        }
        else {
            $dna_input_array[$i];
        }
    }
    return implode($dna_input_array);
}

function helix_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'generated_helix';
}

function helix_success() {
    return 'DNA';
}
